
  development:
  adapter: postgresql
  database: the_wavve
  # encoding: unicode
  # pool: 2
  # username: your_username
  # password: your_password

  production:
  # adapter: postgresql
  # host: <%= ENV['DATABASE_URL'] %> 
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>