
# User.create(first_name: 'Ruby', last_name: 'Gem', birthday: Date.parse("1951-4-11"), industry: 'Advertising', title: 'Account Manager', email: 'ruby.gem@adcompany.com', password: '123abc')
# User.create(first_name: 'Dwayne', last_name: 'Hayes', birthday: Date.parse("1977-5-1"), industry: 'Tech', title: 'Chief Technical Offincer', email: 'bigboss@techcompany.com', password: 'bigboss1')
# User.create(first_name: 'Gordon', last_name: 'Precise', birthday: Date.parse("1982-8-10"), industry: 'Design', title: 'Graphic Designer', email: 'gordonthegreat@designfirm.com', password: 'iluvdesign')



# User.create(first_name: 'Java', last_name: 'theDon', birthday: Date.parse("1971-4-10"), industry: 'Advertising', title: 'CEO', email: 'java.dondatta@adcompany.com', password: 'abc123')


Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Java and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 7)


Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Ruby and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 1)



Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Dwayne and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 2)



Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)
Post.create(img_url: 'fdaflfjdkf', title: "Hi, I'm Gordon and this is my first post", subtitle: 'df;jlkdfja;d', text_content: 'fkad;flddfkdf', user_id: 3)

